from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(986, 774)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 986, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(64, 64))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.action_anasayfa = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/png/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_anasayfa.setIcon(icon)
        self.action_anasayfa.setMenuRole(QtWidgets.QAction.NoRole)
        self.action_anasayfa.setObjectName("action_anasayfa")
        self.action_kayit = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/id/png/id.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_kayit.setIcon(icon1)
        self.action_kayit.setMenuRole(QtWidgets.QAction.NoRole)
        self.action_kayit.setObjectName("action_kayit")
        self.action_yoklama = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/yoklama/png/yoklama.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_yoklama.setIcon(icon2)
        self.action_yoklama.setMenuRole(QtWidgets.QAction.NoRole)
        self.action_yoklama.setObjectName("action_yoklama")
        self.action_kasa = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/kasa/png/kasa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_kasa.setIcon(icon3)
        self.action_kasa.setMenuRole(QtWidgets.QAction.NoRole)
        self.action_kasa.setObjectName("action_kasa")
        self.action_odeme = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/odeme/png/odeme.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_odeme.setIcon(icon4)
        self.action_odeme.setMenuRole(QtWidgets.QAction.NoRole)
        self.action_odeme.setObjectName("action_odeme")
        self.action_egitmen = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/egitmen/png/egitmen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_egitmen.setIcon(icon5)
        self.action_egitmen.setMenuRole(QtWidgets.QAction.NoRole)
        self.action_egitmen.setObjectName("action_egitmen")
        self.action_cikis = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/cikis/png/cikis.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_cikis.setIcon(icon6)
        self.action_cikis.setMenuRole(QtWidgets.QAction.NoRole)
        self.action_cikis.setObjectName("action_cikis")
        self.action_kapat = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/kapat/png/kapat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_kapat.setIcon(icon7)
        self.action_kapat.setMenuRole(QtWidgets.QAction.NoRole)
        self.action_kapat.setObjectName("action_kapat")
        self.toolBar.addAction(self.action_anasayfa)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_kayit)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_yoklama)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_kasa)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_odeme)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_egitmen)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_cikis)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_kapat)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_anasayfa.setText(_translate("MainWindow", "Anasayfa"))
        self.action_anasayfa.setToolTip(_translate("MainWindow", "Anasayfa"))
        self.action_kayit.setText(_translate("MainWindow", "Kayıt"))
        self.action_kayit.setToolTip(_translate("MainWindow", "Kayıt"))
        self.action_yoklama.setText(_translate("MainWindow", "Yoklama"))
        self.action_yoklama.setToolTip(_translate("MainWindow", "Yoklama"))
        self.action_kasa.setText(_translate("MainWindow", "Kasa"))
        self.action_odeme.setText(_translate("MainWindow", "Ödeme"))
        self.action_odeme.setToolTip(_translate("MainWindow", "Ödemeler"))
        self.action_egitmen.setText(_translate("MainWindow", "Eğitmen"))
        self.action_egitmen.setToolTip(_translate("MainWindow", "Eğitmenler"))
        self.action_cikis.setText(_translate("MainWindow", "Çıkış"))
        self.action_cikis.setToolTip(_translate("MainWindow", "Çıkış Yap"))
        self.action_kapat.setText(_translate("MainWindow", "Kapat"))
        self.action_kapat.setToolTip(_translate("MainWindow", "Uygulamayı Kapat"))
from static.rc import pic_rc
